#!/usr/bin/env bash
# This script will display the numbers from 1-100
# Fizzbuzz when muliple of 3 && 5
# Fizz when multiple of 3
# Buzz when multiple of 5

n=1
while [ $n -le 100 ]
do
    if [ $(( n % 3 )) == 0 ] && [ $(( n % 5)) == 0 ]
    then
	echo "FizzBuzz"
    elif [ $(( n % 3 )) == 0 ]
    then
        echo "Fizz"

    elif [ $(( n % 5 )) == 0 ]
    then
         echo "Buzz"
    else
        echo "$n"
    fi
    let n=n+1
done
