#!/usr/bin/env bash
# This script will loop to 10 printing Holberton School, 4th bad, 8th good

n=0
while [ $n -lt 10 ]
do
   echo "Holberton School"
   ((n++))
   if [ $n -eq 4 ]
   then
       echo "bad luck"
   elif [ $n -eq 8 ]
   then
       echo "good luck"
   fi
done