#!/usr/bin/env bash
# This script will display numbers from 1:20 bl from china 4th loop
# bl from Japan 9th loop, bad luck from italy 17th loop

n=1
while [ $n -le 20 ]
do
    echo $n
    case $n in
        4) echo "bad luck from China"
	   ;;
	9) echo "bad luck from Japan"
	   ;;
	17) echo "bad luck from Italy"
	    ;;
    esac
    let n=n+1
done
