#!/usr/bin/env bash
# This script will install nginx on webserver, return holberton school w/ curl
sudo apt-get update
sudo apt-get -y install nginx
echo 'Holberton School' | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart