#!/usr/bin/env bash
# This bash script will be resolving our localhost from 127.0.0.1 - 2
# Along with facebook.com
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
